# Generated by Django 5.0.1 on 2024-02-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
